apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-react
  labels:
      app: front-react
spec:
  selector:
    matchLabels:
      app: front-react
  replicas: 1
  template:
    metadata:
      labels:
        app: front-react
        tier: service
    spec:
      containers:
        - name: node-backend
          image: lparq-front-react:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-react
  labels:
    app: front-react
    tier: service
spec:
  selector:
    app: front-react
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

