apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-busca
  labels:
      app: mss-busca
spec:
  selector:
    matchLabels:
      app: mss-busca
  replicas: 1
  template:
    metadata:
      labels:
        app: mss-busca
        tier: service
    spec:
      containers:
        - name: node-backend
          image: lparq-mss_busca:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mss-busca
  labels:
    app: mss-busca
    tier: service
spec:
  selector:
    app: mss-busca
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

